export const caracteresDeControle = [
  { nome: 'NUL', fullNome: 'NULL', descricao: 'É um caractere de controle usado para indicar a ausência de informação. Geralmente é usado para fins de preenchimento.' },
  { nome: 'SOH', fullNome: 'Start of Heading', descricao: 'Indica o início de um cabeçalho em uma mensagem.' },
  { nome: 'STX', fullNome: 'Start of Text', descricao: 'Marca o início do texto real em uma mensagem.' },
  { nome: 'ETX', fullNome: 'End of Text', descricao: 'Indica o fim do texto em uma mensagem.' },
  { nome: 'EOT', fullNome: 'End of Transmission', descricao: 'Marca o fim da transmissão de uma mensagem.' },
  { nome: 'ENQ', fullNome: 'Enquiry', descricao: 'Usado para solicitar uma resposta do dispositivo receptor.' },
  { nome: 'ACK', fullNome: 'Acknowledgement', descricao: 'Indica que o dispositivo receptor recebeu e processou com sucesso uma mensagem.' },
  { nome: 'BEL', fullNome: 'Bell', descricao: 'Aciona um sinal sonoro audível ou visual.' },
  { nome: 'BS', fullNome: 'Backspace', descricao: 'Move o cursor uma posição para trás.' },
  { nome: 'HT', fullNome: 'Horizontal Tab', descricao: 'Move o cursor para a próxima posição de tabulação horizontal.' },
  { nome: 'LF', fullNome: 'Line Feed', descricao: 'Avança o cursor para a próxima linha.' },
  { nome: 'VT', fullNome: 'Vertical Tab', descricao: 'Move o cursor para a próxima posição de tabulação vertical.' },
  { nome: 'FF', fullNome: 'Form Feed', descricao: 'Avança o cursor para a próxima página ou forma.' },
  { nome: 'CR', fullNome: 'Carriage Return', descricao: 'Move o cursor para o início da linha.' },
  { nome: 'SO', fullNome: 'Shift Out', descricao: 'Indica uma mudança temporária para um conjunto de caracteres diferente, como ASCII extendido.' },
  { nome: 'SI', fullNome: 'Shift In', descricao: 'Volta ao conjunto de caracteres original após o uso de SO.' },
  { nome: 'DLE', fullNome: 'Data Link Escape', descricao: 'Usado em comunicação de dados para indicar que o próximo caractere deve ser interpretado de forma especial.' },
  { nome: 'DC1', fullNome: 'Device Control 1', descricao: 'Usado para controlar dispositivos periféricos.' },
  { nome: 'DC2', fullNome: 'Device Control 2', descricao: 'Outro caractere de controle usado para controlar dispositivos periféricos.' },
  { nome: 'DC3', fullNome: 'Device Control 3', descricao: 'Outro caractere de controle usado para controlar dispositivos periféricos.' },
  { nome: 'DC4', fullNome: 'Device Control 4', descricao: 'Outro caractere de controle usado para controlar dispositivos periféricos.' },
  { nome: 'NAK', fullNome: 'Negative Acknowledgement', descricao: 'Indica que ocorreu um erro durante a transmissão e a mensagem deve ser reenviada.' },
  { nome: 'SYN', fullNome: 'Synchronous Idle', descricao: 'Usado em comunicação de dados para sincronizar os dispositivos.' },
  { nome: 'ETB', fullNome: 'End of Transmission Block', descricao: 'Indica o fim de um bloco de dados.' },
  { nome: 'CAN', fullNome: 'Cancel', descricao: 'Usado para interromper uma sequência de dados.' },
  { nome: 'EM', fullNome: 'End of Medium', descricao: 'Indica o fim de um meio de armazenamento ou transmissão.' },
  { nome: 'SUB', fullNome: 'Substitute', descricao: 'Substitui um caractere que não pode ser representado.' },
  { nome: 'ESC', fullNome: 'Escape', descricao: 'Indica que o próximo caractere deve ser interpretado de forma especial.' },
  { nome: 'FS', fullNome: 'File Separator', descricao: 'Usado para separar e identificar arquivos em um fluxo de dados.' },
  { nome: 'GS', fullNome: 'Group Separator', descricao: 'Usado para separar e identificar grupos de dados relacionados.' },
  { nome: 'RS', fullNome: 'Record Separator', descricao: 'Usado para separar e identificar registros em um fluxo de dados.' },
  { nome: 'US', fullNome: 'Unit Separator', descricao: 'Usado para separar e identificar unidades de dados em um fluxo de dados.' },
];

export const controlChar = [
  'NUL (NULL)',
  'SOH (Start of Heading)',
  'STX (Start of Text)',
  'ETX (End of Text)',
  'EOT (End of Transmission)',
  'ENQ (Enquiry)',
  'ACK (Acknowledgement)',
  'BEL (Bell)',
  'BS (Backspace)',
  'HT (Horizontal Tab)',
  'LF (Line Feed)',
  'VT (Vertical Tab)',
  'FF (Form Feed)',
  'CR (Carriage Return)',
  'SO (Shift Out)',
  'SI (Shift In)',
  'DLE (Data Link Escape)',
  'DC1 (Device Control 1)',
  'DC2 (Device Control 2)',
  'DC3 (Device Control 3)',
  'DC4 (Device Control 4)',
  'NAK (Negative Acknowledgement)',
  'SYN (Synchronous Idle)',
  'ETB (End of Transmission Block)',
  'CAN (Cancel)',
  'EM (End of Medium)',
  'SUB (Substitute)',
  'ESC (Escape)',
  'FS (File Separator)',
  'GS (Group Separator)',
  'RS (Record Separator)',
  'US (Unit Separator)',
  '[Ø]'
];